language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: "BJC4qwMQPE1K200XLzR7xU+tadUx+ojJ2KG7ACaueOKRBcWzU6O1l+Ou3iYPp0A2Jk2CQEH51x5eppV6H8RwsPXdplhUa7kU3pSgD3iHeF90WklS/OryfURWV7q5sjZ/WN06DpkxMk+vF5kRkB4+7euqjcuUvrSUCsKQcN/uKKE="
  app: protected-garden-89563
