language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: g//soAJpZkjKZAPFhsHHfckVjX66wRFSxkzcovMt0KaQdP1aCk2T+xRKESnSXyRrTNJ3d0ow8YRQvqLIbKJO7ObND1Yertz+waRZjZ6R3+A4X+zTrYUCux1A0TMp0QwRQ/zyMaE5DgAO/tdcxTHbAbULru+Q0RzW5i6vlN7AekQ=
  app: protected-garden-89563
on:
  repo: damorton/java-getting-started
