language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: "Ls4iU4zCnDg+KsgAJUvglnH6epg0JtX5Y9J2nusytBrNocnm0/zYFzNFHKvk7OfsTWSCXidjdJoCkitlpQkkHa7zgaxlvVCFzaYSZre1K6wmz6Rop9jWy6aVBRIHutcJM2dz39hO9pHz+n05LjTns73SOST512tCWxvA+0rGBDg="
  app: protected-garden-89563
