language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: "Alzw2PI/aXL31Dw9A+kXX0jdxkrYkVXXto1vdfcj6G/G1Zo1Y0MAD7gohjlvcUJh64rh6XW1ExzMWCU5NWTLEsg+M587Rge+iREWcVkQ4AuAKBA/IlHKKvjUbQ9kp2hESTF1HeSsjtKOvIbUEDf0Xi20PoIDRPzoVK1t68gh5pIOJEq4n/q6/CQwDzn0gxmsf+j9WDO+xhzPGlzt3d99pEQRyOFXfjoZzsyC3KWm2eIteaLTMIBEE1Y+tqRkJ/LmpVNX8qGiDVrEEKBqkbwmKOY/fFakVq2sgQ2w+UXEVGSss/Qssnkeql8GYEuMuF83mkiYSMzL7sN/kCdGkUmJ3q5Po0vVqy9g+9MBOQgX8++3DsXByPZoK2ayHY2nNgh3azRiv3NKrwzxfMEH/jilzo48350ZsDgLizQQiifhlsy7DuTkgpTflJziLnKjSCG9wWYzdl+biy9Th2KGPx3Ra86m4YxDJAxZQCdH4TnAhv9wz1r48kvFy+eQmoi0aymAOvqIwoFVbNGbT5eikXalOjfCKRz8AKzK0Aox8c59mGNtwKqEC7QJiyhNRJkV4iKtuC6F8k7hF38I48keN34QBeaQaqR5+eHrnWVLA8Y8srLOCJHXhPLojb5BvHEZSgsPQlB7u6PkxCR+mbeZTLTHjP6nQmF1HfAmccrsRQB4R/M="
  app: protected-garden-89563
